name = "Saisei Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2332c5c28defd5f390d676e462477ac66aca5a4f7078e60c00b62724d513d69"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
