name = "Saisei Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7017575815b26a77944867fc1da6eb15a3017fc387131bff836a63ac0a247cfd"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
