name = "Saisei Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08b23632bf2188caf5660f412b2e263c49d83eda07d31cd68e23673cbaa2c16a"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
