name = "Saisei Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71427c511158cf6fca062c8c0c7301dbb5308ad8acaf1525390b9a9dd99f0262"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
