name = "Saisei Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eddc0a976c143c140cb4d4a91cce9cf6d3cfa66a8a303fb15303983b89f759fd"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
