name = "Saisei Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60826526bda8f6bf5b4d7ac3254e250d2f755912a3a4de738a767859e6ebbfd3"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
