name = "Saisei Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb1ca7de62ee439c6f01a6927e15942f9fbdb063a32712f110ca4aa21f943ae8"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
