name = "Saisei Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68fc49faaddb1012c4d267aea995dfd69be3aba46a1c410de81486c966acc05c"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
