name = "Saisei Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea0ca87f101cc6d5b5749c074bc1c09fe3f5b70ca711330e92a4e577a92a75aa"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
