name = "Saisei Packwiz"
author = "Dartis XUI"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b39fdfd1df5916a7a6e1e1a71b92fb2e6713305baa49ea075a3313d56593e560"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
